### ISSUE TITLE
Extract specific file without subdirectories

### ISSUE THREAD

**Issue by naub1n** [r-lib/archive#27]
Hi,

it's possible to extract a specific file to a specific directory without all directories in archive file?

**Exemple** 
Create new zip file with one subdirectory
```
a <- archive(system.file(package = "archive", "extdata", "data.zip"))
d <- tempfile()
archive_extract(a, d, c("iris.csv", "airquality.csv"))
dir.create(paste(d,"TEST", sep = "\\"))
file.rename(paste(d,"iris.csv", sep = "\\"), paste(d,"TEST", "iris.csv", sep = "\\"))
z <- tempfile(fileext = ".zip")
archive_write_dir(z,d)
archive(z)
```
Result:
```
> archive(z)
# A tibble: 2 x 3
  path            size date               
  <chr>          <dbl> <dttm>             
1 airquality.csv   142 2017-04-28 21:55:29
2 TEST/iris.csv    192 2017-04-28 21:55:29
```
Extract file iris.csv
```
td <- tempfile()
archive_extract(z,td,"TEST/iris.csv")
list.files(td,recursive = T)
```
Result:
```
> list.files(td,recursive = T)
[1] "TEST/iris.csv"
```

But i only want iris.csv in my temporary directory like that
```
> list.files(td,recursive = T)
[1] "iris.csv"
```

Thx

**Comment by jimhester** [comment]
No, it is not currently possible.

If we were to add this it would be soemthing akin to `--strip-components` in bsdtar

https://github.com/libarchive/libarchive/blob/0fd2ed25d78e9f4505de5dcb6208c6c0ff8d2edb/tar/util.c#L338-L375

**Comment by jimhester** [comment]
Ok we now have a `strip_components` argument that works the same as the command line version.
