### ISSUE TITLE
Put on CRAN?

### ISSUE THREAD

**Issue by mikejohnson51** [r-lib/archive#28]
Hi, this package works wonders for 7z products in R. Thank you!

Are there any plans for it to return to CRAN? It would be useful as a dependency for packages aiming for a CRAN submission. 

Mike

**Comment by jimhester** [comment]
archive was never on CRAN. I submitted it to CRAN over two years ago, on July 28th 2017. Despite the connections API being advertised as for use in packages, it was retroactively changed during development of the archive package by CRAN / R-core members to be a public, but not official part of the API. As a result it now causes a NOTE to be generated

```
* checking compiled code ... NOTE
File 'archive/libs/i386/archive.dll':
  Found non-API call to R: 'R_new_custom_connection'
File 'archive/libs/x64/archive.dll':
  Found non-API call to R: 'R_new_custom_connection'
```

There is no way for me to remove this NOTE and retain the package functionality and CRAN will not accept the package with this NOTE, so I cannot put this on CRAN.

**Comment by mikejohnson51** [comment]
My mistake! I thought I saw it in the CRAN archive. Thank you for taking the time to post a clear explaination.

**Comment by jimhester** [comment]
I will keep this open so people can see why it is not on CRAN.

**Comment by cboettig** [comment]
`archive` is now (2021-06-30) on CRAN!

@jimhester :clap: Now you have to tell us all how you managed to do it despite the hurdles above!

**Comment by jimhester** [comment]
When jumping hurdles it is best not to look back ;)
