### ISSUE TITLE
Support for .lz (lzip) files

### ISSUE THREAD

**Issue by JMcrocs** [r-lib/archive#52]
For now .lz (lzip) file are unrecognized format. would it be possible to change this?

```r
download.file(url = "https://parltrack.org/dumps/ep_votes.json.lz",
              destfile = "ep_votes.json.lz",
               mode = "wb")
archive("ep_votes.json.lz")
# Erreur : archive.cpp:37 archive_read_open1(): Unrecognized archive format
```

**Comment by jimhester** [comment]
lzip is a compression format, not an archive format, e.g. it compresses only a single file, it does not store multiple files like a zip or tar archive would.

So you need to use `archive::file_read()` rather than `archive()`.

e.g.

```r
data <- jsonlite::parse_json(archive::file_read("ep_votes.json.lz"), simplifyVector=FALSE)
```

**Comment by r2evans** [comment]
@jimhester , if `format="lzma"`, do you think that `archive_read` could internally call `file_read` (perhaps with a message/warning)? (I'm just learning the `archive` package, tbh, so I might be missing something obvious.)
