### ISSUE TITLE
Can I change session timeout time length?

### ISSUE THREAD

**Issue by tianfeiwei** [r-lib/archive#76]
I tried to read multiple urls in a for loop but the timeout warning message randomly come out when load 2nd, 3rd, etc. files. Would that possible to change the session timeout time length for a longer time? 
Here is the code example and warning message:
 `dat <- read.csv(archive::archive_read(urls[3], file = 2))`
`Warning: URL 'https://www.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/MCRAdvPartDEnrolData/Downloads/2015/Oct/State-County-Penetration-MA-2015-10.zip': Timeout of 60 seconds was reachedError in file(archive, "rb") : 
  cannot open the connection to 'https://www.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/MCRAdvPartDEnrolData/Downloads/2015/Oct/State-County-Penetration-MA-2015-10.zip'`

**Comment by gaborcsardi** [comment]
If you can `traceback()` then you'll probably see that this error is not coming from archive, but from `file()` for which you can change the timeout with the `timeout` option. See `?options`.
